/*
Copyright (c) 2021-2025 Nicolas Beddows <nicolas.beddows@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#ifndef RPIOCONTROLLER_H
#define RPIOCONTROLLER_H

#include <ArduinoJson.h>
#include <pico/util/queue.h>
#include <vector>

#include "i8080_arcade/IIoController.h"
#include "meen_hw/MH_Factory.h"

namespace i8080_arcade
{
    /** Custom SDL io controller.

        A custom io controller targetting Space Invaders i8080 arcade hardware compatible ROMs.
    */
    class RPIoController final : public IIoController
    {
    private:
        // TODO: these pins need to change depending on the device pin configuration,
        //       may be best to pass them in via the config file.
        enum Pin
        {
            DIN = 11,
            CLK = 10,
            CS = 9,
            DC = 8,
            RST = 12,
            BL = 13,
            K0 = 15,
            K1 = 17,
            K2 = 2,
            K3 = 3
        };

        /** Output device width

            Width in pixels.

            @remark This is determined by the hardware:video:width parameter
                    in the config file.
        */
        int width_{};

        /** Output device height

            Height in pixels.

            @remark This is determined by the hardware:video:height parameter
                    in the config file.
        */
        int height_{};

        /** Centre width offset

            The difference in pixels of the width of the attached lcd panel and the width
            of the i8080 arcahde video hardware.

            This is used to centre the output frame on the lcd panel.
        */
        int widthOffset_{};

        /** Centre height offset

            The difference in pixels of the height of the attached lcd panel and the height
            of the i8080 arcade video hardware.

            This is used to centre the output frame on the lcd panel.
        */
        int heightOffset_{};

        // The width/height of the memory controller frame buffers
        int textureWidth_{};
        int textureHeight_{};

        /** The previous video frame

            Stores the previous frame (the back buffer) generated by the i8080 arcade video hardware.

            This allows for a triple buffering system where the first frame is the frame
            being generated, the second frame is the frame being rendered, and the third
            frame, the back buffer, which is used to compare for scanline differences with the
            frame being rendered. This allows for improved rendering performance by not rendering
            scanlines that are identical to the previous frame.
        */
        meen_hw::MH_ResourcePool<std::vector<uint8_t>>::ResourcePtr backBuffer_;

        /** i8080_arcade

            The hardware emulator.
        */
        std::unique_ptr<meen_hw::MH_II8080ArcadeIO> i8080ArcadeIO_;

        /** Video frame to render queue

            A double element queue used to render the current frame while generating the next frame.
        */
        queue_t videoFrameQueue_;

        /** Available frame queue

            Remainder frames (ones that are not being rendered or generated).
        */
        queue_t freeQueue_;

        /** VideoFrameWrapper

            A convenience wrapper used to pass unique pointers through RP2040s C based queue api.
        */
        struct VideoFrameWrapper
        {
            meen_hw::MH_ResourcePool<std::vector<uint8_t>>::ResourcePtr videoFrame;
        };

        /** An array of resourcePtr wrappers for use with RP2040s C based queue api

            @remark    these wrappers are solely accessed via queues to implement double buffering.
        */
        VideoFrameWrapper videoFrameWrapper_[2];

        /** Video frame buffer

            The pixels that will be rendered to the display.
        */
        std::vector<uint8_t> texture_;

        /** The number of remaining ships

            This counter is used to track when to move from gameplay mode to
            attraction screen mode and vice versa.
            When it is greater than 0, we are in gameplay mode and buttons 0
            and 3 will be used to move the ship left and right. When it is
            0 we are in attraction screen mode and these buttons will be used
            to select which rom to load.
        */
        int ships_{};

        /** Button state tracking

            Store the previous state of the buttons to eliminate
            repeated presses when the button is held down.
        */
        bool lastK0_{};
        bool lastK1_{};
        bool lastK2_{};
        bool lastK3_{};

        bool runAsync_{};

        /** The current screen

            See the Screen enumeration for further details.
        */
        Screen screen_{};

        /** LCD command

            Write a command to the LCD driver.
        */
        static void WriteCmd(uint8_t cmd);

        /** LCD params

            Write command parameters to the LCD driver.

            @param    param    The next parameter in the parameter sequence defined
                               by the previous call to WriteCmd.
        */
        static void WriteParam(uint8_t param);

        /** Ram write region

            Define a region in display ram where pixels can be written to.

            @param    startX    The starting x coordinate of the blit region.
            @param    startY    The starting y coordinate of the blit region.
            @param    endX      The ending x coordinate of the blit region.
            @param    endX      The ending x coordinate of the blit region.
        */
        static void SetRegion(uint16_t Xstart, uint16_t Ystart, uint16_t Xend, uint16_t Yend);

        /** Single button press

            Returns the state of tthe button (ignoring repeats).

            bool    button        True of the button is currently pressed.
            bool    lastButton    The prevos state of the button parameter.
                                  True this is a button repeat, false otherwise.

            return                True for a single press, false otherwise.
        */
        bool ButtonPress(bool button, bool& lastButton);

    public:
        /** Initialisation constructor

            Creates an RP2040 specific i8080 arcade IO controller.

            @param		runAsync		Run this io controller asynchronously.
            @param		audioHardware	audio hardware configuration options.
            @param		videoHardware	video hardware configuration options.

        */
        RPIoController(bool runAsync, const JsonVariantConst audioHardware, const JsonVariantConst videoHardware);

        /** Destructor

            Free the various required RP2040 objects.
        */
        ~RPIoController();

        /** IController Read override

            Sample the keyboard so the CPU can take any required action.

            @param  port    The device to read from.

            @return int             A bitfield indicating the action to take.
        */
        uint8_t Read(uint16_t port, meen::IController* memoryController) final;

        /** IController write override

            Write the relevant audio sample to the output audio device.

            @param  port    The output device to write to.
            @param  data    A bitfield indicating what data to write.
        */
        void Write(uint16_t port, uint8_t data, meen::IController* memoryController) final;

        /** IController::ServiceInterrupts override

            Render the video ram texture to the window via the rendering context.

            @param  currTime        The current CPU run time in nanoseconds.
            @param  cycles          The number of CPU cycles completed.
        */
        meen::ISR ServiceInterrupts(uint64_t currTime, uint64_t cycles, meen::IController* memoryController) final;

        /** Uuid

            Unique universal identifier for this controller.

            @return    The uuid as a 16 byte array.
        */
        std::array<uint8_t, 16> Uuid() const final;

        /** Load Video Textures

            Create the video texture that will be rendered to the screen.

            @param  videoTextures   JSON object describing the video texture.
            @param  textureWidth    The width of the videc texture in pixels.
            @param  textureHeight   The height of the video texture in pixels.

			@return					An error in the form of a std::error_code.
        */
        std::error_code LoadVideoTextures(const JsonVariantConst videoTextures, int textureWidth, int textureHeight) final;

   		/** Load Audio Samples

            Loads the audio samples from the configuration file.

			@param	audioSamples	JSON object representing the audio sample files.

			@return					An error in the form of a std::error_code.
		*/
        std::error_code LoadAudioSamples(const JsonVariantConst audioSamples) final;

        /** Main control loop

            Process all incoming events.

            @return                 True to quit the machine, false otherwise.

            @remark                 This method will always return false, ie; the loop
                                    will run until the device is switched off.
        */
        bool HandleEvent() final;

        /** Error handler

            Process any generated errors

            These errors may come from meen or i8080-arcade itself.

            @param    errorMsg      The error message.
        */
        void HandleError(std::string&& errorMsg) final;

        /** Load the selected rom or the save state of the currently selected rom

        @param    maxSize            The total number of roms in the rom list

        @return                      A tuple holding two values:
                                     bool - only valid when loading roms, true if the save file is to be loaded, false if the rom is to be loaded.
                                     int - the index into the roms array for the rom to be loaded or saved
        */
        std::tuple<bool, int> GetRomIndex(int maxSize) final;
    };
} // namespace i8080_arcade
#endif // RPIOCONTROLLER_H
