.section .rodata
.global rpConfigStart
rpConfigStart:
.incbin "config.json"
.global rpConfigEnd
rpConfigEnd:
.global invadersHStart
invadersHStart:
.incbin "invaders-h.bin"
.global invadersHEnd
invadersHEnd:
.global invadersGStart
invadersGStart:
.incbin "invaders-g.bin"
.global invadersGEnd
invadersGEnd:
.global invadersFStart
invadersFStart:
.incbin "invaders-f.bin"
.global invadersFEnd
invadersFEnd:
.global invadersEStart
invadersEStart:
.incbin "invaders-e.bin"
.global invadersEEnd
invadersEEnd:
.global invdeluxHStart
invdeluxHStart:
.incbin "invdelux-h.bin"
.global invdeluxHEnd
invdeluxHEnd:
.global invdeluxGStart
invdeluxGStart:
.incbin "invdelux-g.bin"
.global invdeluxGEnd
invdeluxGEnd:
.global invdeluxFStart
invdeluxFStart:
.incbin "invdelux-f.bin"
.global invdeluxFEnd
invdeluxFEnd:
.global invdeluxEStart
invdeluxEStart:
.incbin "invdelux-e.bin"
.global invdeluxEEnd
invdeluxEEnd:
.global invdeluxDStart
invdeluxDStart:
.incbin "invdelux-d.bin"
.global invdeluxDEnd
invdeluxDEnd:
.global lrescue1Start
lrescue1Start:
.incbin "lrescue-1.bin"
.global lrescue1End
lrescue1End:
.global lrescue2Start
lrescue2Start:
.incbin "lrescue-2.bin"
.global lrescue2End
lrescue2End:
.global lrescue3Start
lrescue3Start:
.incbin "lrescue-3.bin"
.global lrescue3End
lrescue3End:
.global lrescue4Start
lrescue4Start:
.incbin "lrescue-4.bin"
.global lrescue4End
lrescue4End:
.global lrescue5Start
lrescue5Start:
.incbin "lrescue-5.bin"
.global lrescue5End
lrescue5End:
.global lrescue6Start
lrescue6Start:
.incbin "lrescue-6.bin"
.global lrescue6End
lrescue6End:
.global pv01Start
pv01Start:
.incbin "PV.01"
.global pv01End
pv01End:
.global pv02Start
pv02Start:
.incbin "PV.02"
.global pv02End
pv02End:
.global pv03Start
pv03Start:
.incbin "PV.03"
.global pv03End
pv03End:
.global pv04Start
pv04Start:
.incbin "PV.04"
.global pv04End
pv04End:
.global pv05Start
pv05Start:
.incbin "PV.05"
.global pv05End
pv05End:
.global tn01Start
tn01Start:
.incbin "tn01.bin"
.global tn01End
tn01End:
.global tn02Start
tn02Start:
.incbin "tn02.bin"
.global tn02End
tn02End:
.global tn03Start
tn03Start:
.incbin "tn03.bin"
.global tn03End
tn03End:
.global tn04Start
tn04Start:
.incbin "tn04.bin"
.global tn04End
tn04End:
.global tn05Start
tn05Start:
.incbin "tn05-1.bin"
.global tn05End
tn05End:
